### ISSUE TITLE
hash mismatch in zig.zon

### ISSUE THREAD

**Issue by pwbh** [andrewrk/sdl-zig-demo#15]
It seems that there is a hash mismatch for zig 0.12, so its not possible to run this example at the moment.

```
Fetch Packages [2/1] sdl... /Users/pwbh/Workspace/sdl-zig-demo/build.zig.zon:7:21: error: hash mismatch: manifest declares 12206de2e590f0866e7d96a5e60dd352ec28c7006c7a883c9ede84e25b6c61c7c088 but the fetched package has 122006f1d25dd112605ad00929f05e05da844decd4bc25996998814704344be87a09
            .hash = "12206de2e590f0866e7d96a5e60dd352ec28c7006c7a883c9ede84e25b6c61c7c088",
```

Note sure if its my machine thing, I am on mac with arm processor.

**Comment by ThibaultLemaire** [comment]
My guess is the hash algorithm has changed between zig 0.12.0-dev.1239+ffa20ff72 and 0.12.0, hence the mismatch for the same source input.

#16 should work for you

**Comment by pwbh** [comment]
@ThibaultLemaire I've actually gone ahead and made a stable version of SDL that I maintain now - https://github.com/pwbh/SDL
